import Link from "next/link";
import { redirect } from "next/navigation";
import { db, syncExpiredCancellations } from "@/lib/db";
import { getSession } from "@/lib/auth";
import { messages } from "@/lib/i18n";
export default async function Admin({ searchParams }: { searchParams: Promise<{ store?: string; password?: string }> }) {
  const user = await getSession(); if (!user || user.role !== "ADMIN") redirect("/pt/entrar?admin=1");
  await syncExpiredCancellations();
  const query = await searchParams; const t = messages("pt"); const stores = await db.store.findMany({ orderBy: { name: "asc" } });
  const selected = stores.find((s) => s.slug === query.store); const where = selected ? { storeId: selected.id } : {};
  const subscriptions = await db.subscription.findMany({ where, include: { client: true, product: true, store: true }, orderBy: { createdAt: "desc" } });
  const active = subscriptions.filter((s) => s.status === "ACTIVE");
  const mrr = active.reduce((sum, s) => sum + s.priceCents, 0);
  const pendingCash = subscriptions.filter((s) => s.paymentMethod === "CASH" && (s.status === "PENDING_PAYMENT" || (s.status === "ACTIVE" && s.currentPeriodEnd <= new Date()))).length;
  return <main className="shell dashboard"><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 18, flexWrap: "wrap" }}><div><div className="eyebrow">Jules Daynos · {t.admin}</div><h1 className="page-title">{t.subscribers}</h1></div><div style={{ display: "flex", gap: 10 }}><a className="btn secondary" href="/api/admin/export">{t.export}</a><form action="/api/auth/logout" method="post"><button className="btn secondary">{t.logout}</button></form></div></div>
    <form className="filters" method="get"><label htmlFor="store">{t.store}</label><select id="store" name="store" defaultValue={selected?.slug || ""}><option value="">{t.allStores}</option>{stores.map((s) => <option key={s.id} value={s.slug}>{s.name}</option>)}</select><button className="btn secondary">Filtrar</button></form>
    {query.password === "success" && <div className="notice">{t.success}</div>}{query.password === "error" && <div className="notice">{t.error}</div>}
    <div className="grid" style={{ marginBottom: 26 }}><article className="card"><span className="pill">Ativos</span><h3>{active.length}</h3></article><article className="card"><span className="pill">MRR</span><h3>€{(mrr / 100).toFixed(2)}</h3></article><article className="card"><span className="pill">Dinheiro pendente</span><h3>{pendingCash}</h3></article><article className="card"><span className="pill">Pagamento em falha</span><h3>{subscriptions.filter((s) => ["PAST_DUE", "UNPAID"].includes(s.status)).length}</h3></article></div>
    <form action="/api/admin/export" method="get" className="filters"><label>Pagamentos de <input aria-label="De" name="from" type="date"/></label><label>até <input aria-label="Até" name="to" type="date"/></label><button className="btn secondary" type="submit">{t.export}</button></form>
    <div className="tablewrap"><table><thead><tr><th>{t.customer}</th><th>{t.product}</th><th>{t.store}</th><th>Compromisso</th><th>{t.payment}</th><th>{t.status}</th><th></th></tr></thead><tbody>{subscriptions.map((s) => <tr key={s.id}><td><Link href={`/admin/clients/${s.client.id}`}>{s.client.name}</Link><br/><span style={{ color: "#72776a" }}>{s.client.email}</span></td><td>{s.product.name}<br/>{s.priceCents > 0 ? `€${(s.priceCents / 100).toFixed(2)}` : t.placeholder}</td><td>{s.store.name}</td><td>{s.commitment}</td><td>{s.paymentMethod === "CASH" ? "Dinheiro" : "Stripe"}</td><td><span className="status">{s.status}</span></td><td>{s.paymentMethod === "CASH" && s.priceCents > 0 && (s.status === "PENDING_PAYMENT" || (s.status === "ACTIVE" && s.currentPeriodEnd <= new Date())) && <form action="/api/admin/cash" method="post"><input type="hidden" name="id" value={s.id}/><button className="btn" type="submit">{t.confirmCash}</button></form>}{s.status !== "CANCELED" && <form action="/api/subscriptions/cancel" method="post" style={{ marginTop: 6 }}><input type="hidden" name="id" value={s.id}/><button className="btn secondary" type="submit">Cancelar</button></form>}</td></tr>)}</tbody></table>{subscriptions.length === 0 && <p className="empty">Sem subscrições.</p>}</div>
    <section className="section"><h2>Segurança da conta</h2><form action="/api/auth/password" method="post" className="card" style={{ maxWidth: 460, minHeight: 0 }}><div className="field"><label>Palavra-passe atual</label><input name="currentPassword" type="password" maxLength={72} required/></div><div className="field"><label>Nova palavra-passe (10–72 bytes)</label><input name="newPassword" type="password" minLength={10} maxLength={72} required/></div><button className="btn" type="submit">Alterar palavra-passe</button></form></section><p className="sub" style={{ marginTop: 18 }}><Link href="/admin/planos">Gestão de planos</Link></p>
  </main>;
}
