import { redirect } from "next/navigation";
import { db } from "@/lib/db";
import { getSession } from "@/lib/auth";
import { messages } from "@/lib/i18n";
export default async function ProductsAdmin() {
  const user = await getSession(); if (!user || user.role !== "ADMIN") redirect("/pt/entrar?admin=1");
  const t = messages("pt"); const [products, stores] = await Promise.all([db.product.findMany({ include: { stores: true, storePrices: true }, orderBy: [{ category: "asc" }, { name: "asc" }] }), db.store.findMany({ where: { isActive: true }, orderBy: { name: "asc" } })]);
  const editor = (p?: typeof products[number]) => <form action="/api/admin/products" method="post" className="card" style={{ minHeight: 0 }}><input type="hidden" name="id" value={p?.id || ""}/><span className="pill">{p?.category === "HEAD_SPA" ? t.spa : t.hair}</span><div className="field"><label>Nome</label><input name="name" defaultValue={p?.name || ""} required/></div><div className="field"><label>Descrição</label><input name="description" defaultValue={p?.description || ""} required/></div><div className="field"><label>Categoria</label><select name="category" defaultValue={p?.category || "HAIRDRESSING"}><option value="HAIRDRESSING">{t.hair}</option><option value="HEAD_SPA">{t.spa}</option></select></div><div className="field"><label>Preço mensal base (cêntimos)</label><input name="monthlyPriceCents" type="number" min="0" step="1" defaultValue={p?.monthlyPriceCents ?? 0} required/></div><div className="field"><label>Desconto Long (%)</label><input name="longDiscountPercent" type="number" min="0" max="100" step="1" defaultValue={p?.longDiscountPercent ?? 0} required/></div><div className="field"><label>Pessoas incluídas (1–4)</label><input name="maxPeople" type="number" min="1" max="4" defaultValue={p?.maxPeople ?? 1} required/></div><div className="field"><label>Sessões mensais Head Spa (1–4; deixe 1 para cabelo)</label><input name="sessionsPerMonth" type="number" min="1" max="4" defaultValue={p?.sessionsPerMonth ?? 1}/></div><div className="field"><label>Lojas disponíveis (preço por loja em cêntimos; vazio usa preço base)</label>{stores.map((s) => <label key={s.id} style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" }}><input type="checkbox" name="storeIds" value={s.id} defaultChecked={p ? p.stores.some((link) => link.storeId === s.id) : true}/>{s.name}<input name={`storePrice_${s.id}`} aria-label={`Preço ${s.name}`} type="number" min="0" step="1" placeholder="base" defaultValue={p?.storePrices.find((price) => price.storeId === s.id)?.monthlyPriceCents}/></label>)}</div><label style={{ display: "flex", gap: 8, alignItems: "center", marginBottom: 15 }}><input type="checkbox" name="isActive" defaultChecked={p?.isActive ?? true}/> Disponível para adesão</label><button className="btn" type="submit">{p ? "Guardar alterações" : "Criar plano"}</button></form>;
  return <main className="shell dashboard"><div className="eyebrow">Jules Daynos · {t.admin}</div><h1 className="page-title">Gestão de planos</h1><p className="sub">Os preços são guardados em cêntimos. Preços confirmados por loja podem ser configurados na base de dados através do modelo PlanStorePrice.</p><h2>Planos e pacotes</h2><div className="grid">{products.map((product) => <section key={product.id}>{editor(product)}</section>)}</div><section className="section"><h2>Novo plano</h2><div className="grid">{editor()}</div></section></main>;
}
