type Locale = "pt" | "en" | "es" | "fr" | "de";
type EmailKind = "welcome" | "payment_failed" | "canceled";
const copy: Record<Locale, Record<EmailKind, { subject: string; body: string; action: string }>> = {
  pt: { welcome: { subject: "Bem-vindo à Jules Daynos", body: "A sua conta está pronta. Pode consultar a sua membership e os pagamentos na sua área de cliente.", action: "Abrir a minha conta" }, payment_failed: { subject: "Ação necessária: pagamento falhado", body: "Não foi possível processar o pagamento da sua membership. Atualize o método de pagamento para evitar uma interrupção.", action: "Ver a minha conta" }, canceled: { subject: "Cancelamento registado", body: "O seu pedido de cancelamento foi registado. A membership mantém-se até ao fim do período pago.", action: "Ver a minha conta" } },
  en: { welcome: { subject: "Welcome to Jules Daynos", body: "Your account is ready. You can view your membership and payments in your customer account.", action: "Open my account" }, payment_failed: { subject: "Action needed: payment failed", body: "We could not process your membership payment. Update your payment method to avoid an interruption.", action: "View my account" }, canceled: { subject: "Cancellation recorded", body: "Your cancellation request has been recorded. Membership remains active through the paid period.", action: "View my account" } },
  es: { welcome: { subject: "Te damos la bienvenida a Jules Daynos", body: "Tu cuenta está lista. Consulta tu plan y tus pagos en tu área de cliente.", action: "Abrir mi cuenta" }, payment_failed: { subject: "Acción necesaria: pago rechazado", body: "No pudimos procesar el pago de tu plan. Actualiza el método de pago para evitar una interrupción.", action: "Ver mi cuenta" }, canceled: { subject: "Cancelación registrada", body: "Hemos registrado tu solicitud. El plan sigue activo hasta el final del periodo pagado.", action: "Ver mi cuenta" } },
  fr: { welcome: { subject: "Bienvenue chez Jules Daynos", body: "Votre compte est prêt. Consultez votre abonnement et vos paiements dans votre espace client.", action: "Ouvrir mon compte" }, payment_failed: { subject: "Action requise : paiement refusé", body: "Nous n’avons pas pu traiter votre paiement. Mettez à jour votre moyen de paiement pour éviter une interruption.", action: "Voir mon compte" }, canceled: { subject: "Résiliation enregistrée", body: "Votre demande est enregistrée. L’abonnement reste actif jusqu’à la fin de la période payée.", action: "Voir mon compte" } },
  de: { welcome: { subject: "Willkommen bei Jules Daynos", body: "Ihr Konto ist bereit. Sie können Ihre Mitgliedschaft und Zahlungen im Kundenbereich ansehen.", action: "Mein Konto öffnen" }, payment_failed: { subject: "Aktion erforderlich: Zahlung fehlgeschlagen", body: "Ihre Mitgliedschaftszahlung konnte nicht verarbeitet werden. Aktualisieren Sie Ihre Zahlungsart, um eine Unterbrechung zu vermeiden.", action: "Mein Konto ansehen" }, canceled: { subject: "Kündigung erfasst", body: "Ihre Kündigung wurde erfasst. Ihre Mitgliedschaft bleibt bis zum Ende des bezahlten Zeitraums aktiv.", action: "Mein Konto ansehen" } },
};
export async function sendNotice(to: string, locale: string, kind: EmailKind) {
  if (!process.env.RESEND_API_KEY || !process.env.EMAIL_FROM) return;
  const text = copy[(Object.keys(copy).includes(locale) ? locale : "pt") as Locale][kind]; const url = `${process.env.APP_URL || "http://localhost:3000"}/${locale}/conta`;
  const response = await fetch("https://api.resend.com/emails", { method: "POST", signal: AbortSignal.timeout(5000), headers: { authorization: `Bearer ${process.env.RESEND_API_KEY}`, "content-type": "application/json" }, body: JSON.stringify({ from: process.env.EMAIL_FROM, to, subject: text.subject, html: `<main style="font-family:Arial,sans-serif;max-width:560px;margin:auto;color:#24271f"><h1 style="font-family:Georgia,serif">Jules Daynos</h1><p>${text.body}</p><p><a href="${url}" style="display:inline-block;padding:12px 18px;background:#344b3d;color:#fff;text-decoration:none;border-radius:6px">${text.action}</a></p></main>` }) });
  if (!response.ok) throw new Error(`Email provider returned ${response.status}`);
}
